version: '3.8'

services:
  db:
    image: postgres:17
    container_name: phonebook_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: phonebook
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - phonebook_network

  app:
    build: .
    container_name: phonebook_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - phonebook_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: phonebook_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - phonebook_network

networks:
  phonebook_network:
    driver: bridge